version: '3.8'


services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: wedev
      POSTGRES_USER: rick
      POSTGRES_PASSWORD: '94082'
  web:
    build: .
    command: python wedev/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
