version: '3.8'


services:
  db:
    image: postgres
    restart: always
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: wedev
      POSTGRES_USER: rick
      POSTGRES_PASSWORD: 94082
    ports:
      - "5432:5432"
  web:
    tty: true
    build: .
    command: bash -c "python wedev/manage.py makemigrations &&
        python wedev/manage.py migrate &&
        python wedev/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: